FROM ruby:3.0.3 as base

ARG BUNDLER_VERSION=2.2.22

# set some default ENV values for the image
ENV RAILS_LOG_TO_STDOUT 1
ENV RAILS_SERVE_STATIC_FILES 1

# set the app directory var
ENV APP_HOME /home/app
WORKDIR $APP_HOME

RUN apt-get update -qq \
  && apt-get install -y --no-install-recommends \
  build-essential \
  curl \
  default-libmysqlclient-dev \
  default-mysql-client \
  dumb-init \
  git \
  libssl-dev \
  libxslt-dev \
  openssh-client \
  unzip \
  zlib1g-dev \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get clean

# install bundler
RUN gem install bundler -v "${BUNDLER_VERSION}"

EXPOSE 3000

# use dumb-init as an init system for our process
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
